# .golangci.yml - compatible with golangci-lint v1.50+ and above
version: "2"
linters:
  enable:
  - gofmt
  - golint
  - govet
  - errcheck
  - staticcheck
  - gosimple
  - ineffassign
  - unused
  - misspell
  - gosec
  - unconvert
  - goconst
  - goimports
  - revive
  - gocyclo
  - dupl
  - gocritic
  - prealloc
  - scopelint
  - stylecheck
  - whitespace

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
