version: 1

linters:
  enable:
  - gofmt
  - golint
  - govet
  - errcheck
  - staticcheck
  - gosimple
  - ineffassign
  - unused
  - misspell
  - gosec
  - unconvert
  - goconst
  - goimports
  - revive
  - gocyclo
  - dupl
  - gocritic
  - prealloc
  - scopelint
  - stylecheck
  - whitespace

run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - gosec
    - dupl
    - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
