### Signup
POST http://0.0.0.0:5001/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "Test User 2",
  "email": "fahire2285@ethsms.com",
  "phone": "+1234567890",
  "password": "TestPassword123!"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "fahire2285@ethsms.com",
  "password": "new-pass-changed"
} 

### Vefify Email
POST http://localhost:5001/api/v1/auth/verify-email
Content-Type: application/json

{
  "token": "email_verify_token"
}

### Forgot password
POST http://localhost:8080/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "fahire2285@ethsms.com"
} 

### Reset password
POST http://localhost:8080/api/v1/auth/reset-password
Content-Type: application/json

{
  "new_password": "newPassword1",
  "token": "reset_token"
}

### Get Profile  
GET  http://localhost:8080/api/v1/profile/8032ef1f-d52b-458b-a983-c05588235e0e
Content-Type: application/json

### update profile
PUT http://localhost:8080/api/v1/profile/8032ef1f-d52b-458b-a983-c05588235e0e
Content-Type: application/json

{
      "id": "8032ef1f-d52b-458b-a983-c05588235e0e",
      "email": "fahire2285@ethsms.com",
      "name": "Test changed 6",
      "phone": "+1234567890"
}

### update password
PATCH http://localhost:8080/api/v1/change-password/8032ef1f-d52b-458b-a983-c05588235e0e
Content-Type: application/json

{
      "current_password": "newPassword1",
      "new_password": "new-pass-changed"
}

### Logout // ACCESS TOKEN is stored in cookie , or you can pass BEARER token through Authorization header
POST   http://localhost:5001/api/v1/auth/logout
Content-Type: application/json
